server:
  port: 8080

spring:
  datasource:
    username: zhaozengjie
    password: 123456
    url: jdbc:mysql://localhost:3306/test
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath*:sqlmap/*Mapper.xml

logging:
  level:
    com:
      example:
        mapper : debug