server:
  port: 8080

spring:
  datasource:
    username: zhaozengjie
    password: 123456
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:datasource/mybatis/sqlmap/*Mapper.xml


logging:
  level:
    com:
      example:
        mapper : debug